<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Perusahaan_input-106</name>
   <tag></tag>
   <elementGuidId>f5ebaad1-1c09-4183-917a-d09153cc9098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-106</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-106']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20891ecc-970c-402a-88c5-269f412cf1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-106</value>
      <webElementGuid>d6628266-12e6-4596-ba5a-e545b8fe2995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc554956-1cac-47f4-a218-ed8a37419490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-106&quot;)</value>
      <webElementGuid>98edbd8e-71cb-4fd3-8f14-47ba4f023aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bc503d3-82a5-4d83-8e62-c446f924ac82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-106</value>
      <webElementGuid>2e0896c4-d1bc-449d-9265-0bf0545ebeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91a0656f-43a5-41b6-875d-681254fdd724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-106&quot;)</value>
      <webElementGuid>1b2be85e-35bd-4049-bfc8-88ebd7f5c187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-106']</value>
      <webElementGuid>a78dc148-6d59-4d4f-af39-92894291617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div[2]/div/div/div/input</value>
      <webElementGuid>72c4b411-e782-4b67-a7bf-a737ae42ff2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5fd6f0ee-8575-4181-9207-6082b4a4a099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-106' and @type = 'text']</value>
      <webElementGuid>1df8d089-e75c-4294-8fdc-c1b80d4674c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
