<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Kata Sandi_input-130</name>
   <tag></tag>
   <elementGuidId>424a75da-e035-4c4e-a79f-8e4d09d57ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-130</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-130']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98b4fef4-4e2a-4ec2-9ad0-84e754a2cd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-130</value>
      <webElementGuid>13072235-80a4-4cac-835b-3f693fe5aa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e61a8934-1f39-411a-a943-1d3408e4ca38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-130&quot;)</value>
      <webElementGuid>c0424560-3f49-4a64-8aba-89a6a3dc97df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8896590-b368-4016-93db-94d73391b309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-130</value>
      <webElementGuid>eaff23be-92e8-47d6-b564-7c92dd5c9077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3c2127fa-cf4d-45e6-ac36-4ce81b4048c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-130&quot;)</value>
      <webElementGuid>5ab52c70-a4ff-45ac-a88d-95ff209cf890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-130']</value>
      <webElementGuid>bd287b3a-2675-4762-87ae-8718e17a0b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div[6]/div/div/div/input</value>
      <webElementGuid>eac158cd-a76e-42e7-a2d2-b3a8c94ea613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>721c8f55-464e-4445-83db-6acef7adf44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-130' and @type = 'password']</value>
      <webElementGuid>9953c664-8180-4036-a9aa-397f4fb8a012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
