<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Perusahaan_input-109</name>
   <tag></tag>
   <elementGuidId>a440ac1e-5cbb-4b42-9ef3-b56d2402bf03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-109</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-109']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d664309-4d3c-4a77-940d-36530997e318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-109</value>
      <webElementGuid>1010a24b-ddd5-4adc-b14a-db5178a4c7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c873557-5bca-4bc0-8715-21c11c3148ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-109&quot;)</value>
      <webElementGuid>4c4b7bac-d3c3-42a6-9efb-aef1f91f1db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bff2d87-2f96-4ee7-8fd4-8d2c04cf8d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-109</value>
      <webElementGuid>cc8e6c33-8cae-416d-aaec-52fc6e0f2dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f2edb60-4f0e-4564-b435-f865d7846a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-109&quot;)</value>
      <webElementGuid>5dc03352-0262-4df4-ad70-7a83764694ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-109']</value>
      <webElementGuid>167547d7-ea24-4d5a-9f1d-09703eab5689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div[3]/div/div/div/input</value>
      <webElementGuid>e6215dff-22cd-463f-b048-0fda46ee1957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>f6dfbe3a-896b-4a7e-991d-aa87eb6971fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-109' and @type = 'text']</value>
      <webElementGuid>d118ecea-2747-462d-87be-ca000857108f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
