<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_input-126</name>
   <tag></tag>
   <elementGuidId>0a4a1323-7233-4611-b484-2cd5be5da936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-126</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-126']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c1d7fb4-e3d2-41a8-8ce8-df40f1463e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-126</value>
      <webElementGuid>63ace917-8930-45ba-a3a4-f0db9eea1100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c61d8445-1f46-44c4-ba16-0cea98e2e20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-126&quot;)</value>
      <webElementGuid>f5eee74c-70b2-4e0a-bac1-adca8848bf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>362d193d-c847-4a19-985a-627b2aca078d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-126</value>
      <webElementGuid>a16fc80e-6f75-4125-b419-4cb06e094cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>60d8eeac-9495-4fc2-8517-d6cff108a5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-126&quot;)</value>
      <webElementGuid>51aa2083-edb6-4a08-aa61-3dac60a19dba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-126']</value>
      <webElementGuid>3172bd17-54fc-4f2b-a4b2-6a1f31866e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div[5]/div/div/div/input</value>
      <webElementGuid>626a5640-c5aa-4dea-ac5e-1a15447ffa3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>319c0814-de64-4b87-99be-7b4b3ee28cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-126' and @type = 'password']</value>
      <webElementGuid>63bd2d34-34ad-4371-8e41-0ae7494ec6a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
