<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Website Perusahaan_input-115</name>
   <tag></tag>
   <elementGuidId>661421d5-7031-430b-a9c8-1df18a4594c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-115</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-115']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6724bcb6-8d5f-468c-8dd5-cc39013dc836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-115</value>
      <webElementGuid>d95d9174-ac6a-4a3f-aad9-ae6206512640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>133c9651-5085-4c47-9d5b-84d8e697c220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-115&quot;)</value>
      <webElementGuid>952a1363-516c-4eb1-9b5a-e71d7dadcb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b652f14e-8779-4612-a6f6-c9a0a83c5c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-115</value>
      <webElementGuid>ec0430ab-00f2-47e0-a1ed-a8378a2939ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc831795-b86d-4af6-952c-7758f3be53cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-115&quot;)</value>
      <webElementGuid>d5a53c5e-4a4a-43a3-8dba-f5a798c56773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-115']</value>
      <webElementGuid>84329da1-0321-45ba-810c-2e9f8ffa7edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div[5]/div/div/div/input</value>
      <webElementGuid>4deb0dcd-7709-4c0c-831d-61c24be84ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>e2c48ffd-8bf4-4008-a797-9a1769656dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-115' and @type = 'text']</value>
      <webElementGuid>0ff01397-d95b-4c06-910e-1858b33c4b4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
