<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bidang Perusahaan_input-112</name>
   <tag></tag>
   <elementGuidId>2c3cd75c-89ad-43fe-b2f2-ef1c6801281a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-112</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-112']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f5eb7ee-d2f8-4413-962d-5a1841a6f332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-112</value>
      <webElementGuid>0ba5d40d-2db2-4109-a5b0-1086b37219f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e2ec0cd-5350-4fb8-b04a-7349cca10fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-112&quot;)</value>
      <webElementGuid>845fc101-8fde-430e-b138-690a3c145409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f094da78-0b6d-4b51-8538-99c4ad3c888c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-112</value>
      <webElementGuid>87bf2a4f-91f0-44d2-beab-534be5991968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ea87e1a-9298-457a-8169-8a91729c4b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-112&quot;)</value>
      <webElementGuid>24690f9f-e740-491c-ba44-15d27942cd26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-112']</value>
      <webElementGuid>057a6d16-aacb-4e5d-9d98-371d2dfe0101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div[4]/div/div/div/input</value>
      <webElementGuid>65128da0-03e0-4f11-ae6d-6027325a9a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>68067ffc-c814-4104-8e6f-0f1940bfad00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-112' and @type = 'text']</value>
      <webElementGuid>8ce5dbe0-9392-44ce-b5b7-737d00c2a291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
