<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih File</name>
   <tag></tag>
   <elementGuidId>2853ad36-2ebd-4f28-b980-b07ce54c8fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.v-btn__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/form/div/header/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04535f93-ac93-4b5e-b26a-4e88680f7185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>ade0724f-276f-4360-879d-0321c062e1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih File </value>
      <webElementGuid>8123fb6d-12b1-422c-8c90-71723fa277a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-7&quot;]/div[@class=&quot;container cont&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;form&quot;]/header[@class=&quot;inputPicture v-sheet v-sheet--outlined theme--light rounded v-toolbar v-toolbar--dense v-toolbar--flat&quot;]/div[@class=&quot;v-toolbar__content&quot;]/button[@class=&quot;text-capitalize 286F6C--text v-btn v-btn--outlined theme--light v-size--small&quot;]/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>12b37acf-a29e-43a7-aade-78e940b85938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e37a2c5-6eb8-4419-b7a7-ed5a799794ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>ebaaaf0d-b4c4-44a2-a251-8c68f3464004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih File </value>
      <webElementGuid>78813b63-8114-4574-8591-6b3df8c4aad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-7&quot;]/div[@class=&quot;container cont&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;form&quot;]/header[@class=&quot;inputPicture v-sheet v-sheet--outlined theme--light rounded v-toolbar v-toolbar--dense v-toolbar--flat&quot;]/div[@class=&quot;v-toolbar__content&quot;]/button[@class=&quot;text-capitalize 286F6C--text v-btn v-btn--outlined theme--light v-size--small&quot;]/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>ea48a54a-1de1-47ca-8774-f54d097998e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/header/div/button/span</value>
      <webElementGuid>c72e81b2-3400-4c78-9f69-57711eb245da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website Perusahaan'])[1]/following::span[1]</value>
      <webElementGuid>f2b1b9c6-05ac-4c31-84df-d6bada64e9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[4]/following::span[1]</value>
      <webElementGuid>75bf4945-7ac9-4891-8418-581e1df4145f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::span[3]</value>
      <webElementGuid>667a03b5-5208-4e07-9e28-e00e7f66cc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih File']/parent::*</value>
      <webElementGuid>9d8449db-2af6-49ac-896b-4be66349a427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>fd27ef2c-f481-45ad-9e53-4912ce6614ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Pilih File ' or . = ' Pilih File ')]</value>
      <webElementGuid>585e4157-c4f2-4e8c-b159-3a7bd7ee6bb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
