<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_tambah kursus</name>
   <tag></tag>
   <elementGuidId>bfd13172-df87-4030-81aa-a8ef151d1e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-capitalize.v-btn.v-btn--has-bg.v-btn--router.theme--light.v-size--default.primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a650c98-5ac4-48dd-ae00-7bdccb70b240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/course/add</value>
      <webElementGuid>5f017e28-d285-4460-905a-8a0a8e5b3751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-capitalize v-btn v-btn--has-bg v-btn--router theme--light v-size--default primary</value>
      <webElementGuid>d033dad7-fef4-423c-adc7-85e8339cb589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> tambah kursus </value>
      <webElementGuid>9a0a29c6-dd0d-4087-ad8f-a7f8335f6dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex mx-auto my-auto header&quot;]/a[@class=&quot;text-capitalize v-btn v-btn--has-bg v-btn--router theme--light v-size--default primary&quot;]</value>
      <webElementGuid>f6587cf6-67f3-4478-9d08-2526444cede1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/a</value>
      <webElementGuid>b51cdf58-9bec-4ea2-b7cc-aa58eabe3100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kursus'])[2]/following::a[1]</value>
      <webElementGuid>f0e6dd31-e0a7-4c58-addb-4040a616f0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::a[1]</value>
      <webElementGuid>e22c6530-c13d-429e-8e8d-8086642a9d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::a[1]</value>
      <webElementGuid>38d7b9c5-7bd8-47a9-82ab-fc5a70b1c18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/course/add')]</value>
      <webElementGuid>1bcdf23a-dcd7-4249-9f3b-657c3e9688b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/a</value>
      <webElementGuid>c6a50ae7-06b8-46bf-a2c1-62b2ed979fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/course/add' and (text() = ' tambah kursus ' or . = ' tambah kursus ')]</value>
      <webElementGuid>84b5a9ef-8fb8-4945-b485-954258555dd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
