<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih File</name>
   <tag></tag>
   <elementGuidId>6eaef6ba-8f1d-4711-9daa-7c3d0f7deff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.text-capitalize.286F6C--text.v-btn.v-btn--outlined.theme--light.v-size--small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>161c4276-340f-469c-93c8-bc6923976a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbb12635-63ba-4c15-94c0-2e9312bb0003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-capitalize 286F6C--text v-btn v-btn--outlined theme--light v-size--small</value>
      <webElementGuid>bf459e53-7cf9-43d2-967d-556b4e39b3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih File </value>
      <webElementGuid>b305d88d-a1bd-4057-a3bf-b166c6e0d5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;detailkursus&quot;]/div[@class=&quot;pa-6 v-card v-sheet theme--light&quot;]/div[@class=&quot;gambar d-flex&quot;]/header[@class=&quot;inputPicture v-sheet v-sheet--outlined theme--light rounded v-toolbar v-toolbar--dense v-toolbar--flat&quot;]/div[@class=&quot;v-toolbar__content&quot;]/button[@class=&quot;text-capitalize 286F6C--text v-btn v-btn--outlined theme--light v-size--small&quot;]</value>
      <webElementGuid>fe964e0b-affa-4dbf-81ed-a99a0d366b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>5a926110-1fa8-4d81-9d20-58c1304e298b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[3]/div/div[3]/header/div/button</value>
      <webElementGuid>3d418826-ddf9-45bb-9171-ca262f6baf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::button[1]</value>
      <webElementGuid>18e21ddd-7b51-42c3-8c8c-f60ec95c8215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='deskripsi kursus'])[1]/following::button[1]</value>
      <webElementGuid>d04aedf5-edd5-49c0-8a2a-381835c0b864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='modul kursus'])[1]/preceding::button[1]</value>
      <webElementGuid>2407b52c-7e32-4693-a22d-ea686810f51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/button</value>
      <webElementGuid>776b2a4a-8326-4c42-9350-728da44c7484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Pilih File ' or . = ' Pilih File ')]</value>
      <webElementGuid>f73cc247-81f8-499a-8e27-09add26bdb8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
