<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kembali tambah kursusMasukan data kursu_b834e9</name>
   <tag></tag>
   <elementGuidId>bae3c35e-1d35-4496-802e-4ac72defc15f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-application--wrap > #app > div.v-application--wrap > #app > div.v-application--wrap > main.v-main > div.v-main__wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='app']/div/main/div)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f56c7a6a-a4db-4889-921f-1c467c729c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-main__wrap</value>
      <webElementGuid>d48e28b4-a967-4bdc-b371-a45314c117c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Kembali tambah kursusMasukan data kursus baru yang ingin kamu buatdetail kursusjudul kursus​ deskripsi kursus ​ Pilih File car-icon-in-flat-style-simple-traffic-icon-free-vector.webpmodul kursus tambah modul  Modul 1  hapus modul nama modul​link slides materi ​Kosongkan bila tidak diperlukan Link Video Materi ​Kosongkan bila tidak diperlukanQuiz tambah soal quiz 1​ A ​ B ​ C ​ D ​​Opsi Jawaban Benar Simpan Kursus </value>
      <webElementGuid>6a00ae2f-edba-4fc3-82da-880a780db08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]</value>
      <webElementGuid>537240f0-69b0-476e-bc50-91d1b55542e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='app']/div/main/div)[2]</value>
      <webElementGuid>1b53cfe4-64b2-49cc-93d5-5f036b05793e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::div[4]</value>
      <webElementGuid>55a7fabe-78ee-410e-a0ef-a209b8f04fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan'])[1]/following::div[7]</value>
      <webElementGuid>c02bcd94-ed4b-4cad-a299-e344f13661cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/main/div</value>
      <webElementGuid>b69ddff5-7398-4123-b4d6-1dd4020b4abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Kembali tambah kursusMasukan data kursus baru yang ingin kamu buatdetail kursusjudul kursus​ deskripsi kursus ​ Pilih File car-icon-in-flat-style-simple-traffic-icon-free-vector.webpmodul kursus tambah modul  Modul 1  hapus modul nama modul​link slides materi ​Kosongkan bila tidak diperlukan Link Video Materi ​Kosongkan bila tidak diperlukanQuiz tambah soal quiz 1​ A ​ B ​ C ​ D ​​Opsi Jawaban Benar Simpan Kursus ' or . = ' Kembali tambah kursusMasukan data kursus baru yang ingin kamu buatdetail kursusjudul kursus​ deskripsi kursus ​ Pilih File car-icon-in-flat-style-simple-traffic-icon-free-vector.webpmodul kursus tambah modul  Modul 1  hapus modul nama modul​link slides materi ​Kosongkan bila tidak diperlukan Link Video Materi ​Kosongkan bila tidak diperlukanQuiz tambah soal quiz 1​ A ​ B ​ C ​ D ​​Opsi Jawaban Benar Simpan Kursus ')]</value>
      <webElementGuid>0996305e-a911-4c9d-8a20-272c28877cc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
