<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-249</name>
   <tag></tag>
   <elementGuidId>4e204793-4d6d-4a19-ad54-957146f173f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-249</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-249']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3677650-ed56-422b-8bef-15e48f82ae07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-249</value>
      <webElementGuid>55ed61b3-258e-4778-8162-35101b8872e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Nama Modul</value>
      <webElementGuid>72af4971-3870-4be5-9726-126f6ab80abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5beb1591-6386-4003-8055-5f05138bf08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-249&quot;)</value>
      <webElementGuid>0b53f9f3-f7dd-4387-942f-911abab60755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-249']</value>
      <webElementGuid>574de3a2-eb54-49e2-ad03-5c96409ed606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>a2401d40-b007-454c-a88c-e8813b4b0ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>c1688aa1-43f1-4343-8432-b9fad6013a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-249' and @placeholder = 'Masukan Nama Modul' and @type = 'text']</value>
      <webElementGuid>1ab2a3c9-de08-4f43-adf8-263af3ddce5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
