<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-267</name>
   <tag></tag>
   <elementGuidId>ea0afab8-cecf-4254-9eb0-ad278e2d9311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-267</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-267']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8de29e3f-d9ab-4e33-a3a5-72949e5387a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-267</value>
      <webElementGuid>4e97dd8c-2256-43d0-9142-9d11875cd15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Opsi B</value>
      <webElementGuid>bf40e261-0b59-45be-a726-ebd8b83eb352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bebd5a4d-419b-4434-ad7a-b691b790b109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-267&quot;)</value>
      <webElementGuid>6ee223c4-f309-4c00-8fb9-aa147315f57a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-267']</value>
      <webElementGuid>c8b7b6db-2d7e-4edc-bb38-f9228bc1dec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div[2]/div[5]/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>3e7f5839-6e16-4d02-a852-0095fa0c87b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>ed1dfdf8-8612-4b6b-abb3-bc9525f79d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-267' and @placeholder = 'Masukan Opsi B' and @type = 'text']</value>
      <webElementGuid>c07a05e4-ecd3-419e-a462-baec744825b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
