<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-269</name>
   <tag></tag>
   <elementGuidId>13efab1b-d2bc-41b0-990b-4b024d236e9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-269</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-269']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5315ec4a-bc7a-4c15-9265-30503903d2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-269</value>
      <webElementGuid>9f977dff-28f6-4165-bc40-7865c68a2544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Opsi C</value>
      <webElementGuid>80645c99-24e1-47a3-a0b6-2f5e43573cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df1068f4-6449-425d-8b87-a79702f4645b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-269&quot;)</value>
      <webElementGuid>1bfe8027-38e6-431d-83c2-926756018ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-269']</value>
      <webElementGuid>81c1dca9-305c-40f5-841c-15166ade20f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div[2]/div[5]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>1df9faf3-ca7d-4dcf-bb0a-c5b2baf1df8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/input</value>
      <webElementGuid>d6759932-a68c-49ca-8874-9ddeedc91af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-269' and @placeholder = 'Masukan Opsi C' and @type = 'text']</value>
      <webElementGuid>3f41d42d-fa5f-468c-87d1-71ac2132fa3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
