<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-232</name>
   <tag></tag>
   <elementGuidId>a03860f5-82d9-4059-85b4-d7a2feb835ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-232</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-232']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13891534-ed0b-4f7a-b091-7e3c3d45c7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-232</value>
      <webElementGuid>125aae4e-84c5-43e1-b39a-774157d995bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Judul Kursus</value>
      <webElementGuid>350fd24b-6db0-4583-81ca-e67476177414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aef03c17-a3e2-40e7-9bce-0e6a63613f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-232&quot;)</value>
      <webElementGuid>b3ef36a0-2bed-468e-8d84-ebf27f61a252</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-232']</value>
      <webElementGuid>a7f7914e-49fe-4896-80a0-d4c1ff945c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>084ee1ba-d2c4-477f-b2a7-85c9666f80fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>671bc2c2-7d04-42da-b8da-f1e80d0c0849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-232' and @placeholder = 'Masukan Judul Kursus' and @type = 'text']</value>
      <webElementGuid>f74f1bb0-7217-43d0-82a6-dd5d1188f9d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
