<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-271</name>
   <tag></tag>
   <elementGuidId>4e8d2b8b-6a94-48a4-9a7c-fe112b2b65f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-271</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-271']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3533dbc1-5d4b-425d-8c83-6aaf9f6646b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-271</value>
      <webElementGuid>c3dc4712-f54e-4714-8306-f169c0bd8f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Opsi D</value>
      <webElementGuid>f6bf4bc5-81d7-41b5-9854-76f4f9f42b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>509201c6-821a-47f4-913a-af29dd8b5353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-271&quot;)</value>
      <webElementGuid>34ecb95c-f4b3-4641-a8a2-954f70376ae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-271']</value>
      <webElementGuid>a37f06bf-4800-46a8-978a-1449862dd28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div[2]/div[5]/div/div[2]/div[2]/div[4]/div/div[2]/div/div/div/input</value>
      <webElementGuid>1cfe800c-7bf8-4777-843e-93b49ea05b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/input</value>
      <webElementGuid>83be528d-b556-44e1-a24b-4e64ff6073f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-271' and @placeholder = 'Masukan Opsi D' and @type = 'text']</value>
      <webElementGuid>2dd38201-b2ca-4450-abb1-bbabd78f8353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
