<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-252</name>
   <tag></tag>
   <elementGuidId>638cd265-8ee7-4a55-888d-6afd7a35e987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-252</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-252']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4697a49d-54be-482d-9c49-73d4f6c32730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-252</value>
      <webElementGuid>859dbb8b-84b2-4274-ac2c-94997067523f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Link Slides Materi</value>
      <webElementGuid>6faeaea8-bfb8-46db-9fad-49b65bea7172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c942c9e1-e72d-4f73-9d12-4ee651ab45bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-252&quot;)</value>
      <webElementGuid>19309928-ea3c-49ef-b312-a481b9d799f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-252']</value>
      <webElementGuid>6adb5f92-fcc9-4ab5-aaac-0d8f8bfb6ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div[2]/div[3]/div/div/div/div/input</value>
      <webElementGuid>acbab27b-d064-4254-9f6a-a4d6e83cc3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>624d8ddf-688b-43e2-b28f-1aab3ba51109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-252' and @placeholder = 'Masukan Link Slides Materi' and @type = 'text']</value>
      <webElementGuid>03fc7d95-91d7-4684-b574-411c548363dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
