<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-255</name>
   <tag></tag>
   <elementGuidId>f3483ea9-224c-4380-8352-bb52172e1900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-255</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-255']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6701b676-9427-4d4d-a9c5-d35ee1f1244e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-255</value>
      <webElementGuid>e5eafaba-2ca7-4af5-abf2-cdfd3a0181e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Link Video Presentasi</value>
      <webElementGuid>3e3fc405-3aa9-46af-9c01-685648ae9263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a15a6cf4-27d2-4808-995a-173273d4b82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-255&quot;)</value>
      <webElementGuid>adea47fb-8691-478e-9b50-ec254da535f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-255']</value>
      <webElementGuid>6d7744e0-9cab-4e6c-91a9-10e50c17a8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div[2]/div[4]/div/div/div/div/input</value>
      <webElementGuid>5150c2fe-df84-4f64-8778-05dd5b7514ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>cfb78e87-fbb9-433f-a22f-b009bcdcc3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-255' and @placeholder = 'Masukan Link Video Presentasi' and @type = 'text']</value>
      <webElementGuid>b3ccf903-8c62-4747-9c28-a922a89af765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
