<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-265</name>
   <tag></tag>
   <elementGuidId>2b813efe-e56a-4513-ad47-4ab0aa2a03b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-265</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-265']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30c56ebc-bce9-4031-80d1-5db1a2705438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-265</value>
      <webElementGuid>4c0055df-ab6f-4429-9728-d8d5c77a1a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Opsi A</value>
      <webElementGuid>c7f57efd-c66d-432e-a6fe-38ae4f2402fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>064b3474-f1e2-4519-b153-b23668b589c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-265&quot;)</value>
      <webElementGuid>45a34853-96dc-47d0-8553-2f25f254d5ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-265']</value>
      <webElementGuid>3c28fb9c-3445-4bf2-978a-0fa271dd6b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div[2]/div[5]/div/div[2]/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>134e06c5-c433-4cda-a493-a2a31537f3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>d089827b-c732-4422-bc15-7928d0a20719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-265' and @placeholder = 'Masukan Opsi A' and @type = 'text']</value>
      <webElementGuid>21116e6e-cfbf-4bf3-bd33-c792ec70f801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
