<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__input-261</name>
   <tag></tag>
   <elementGuidId>e098ed2e-3f89-47f8-9b9b-5f9250f8b04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-261</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-261']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0a8e3519-c1f2-4cc7-9ce0-76200b227e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-261</value>
      <webElementGuid>330f4398-4205-4c91-a6dc-b1575c134b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tuliskan Pertanyaan Disini</value>
      <webElementGuid>465d958c-3020-4c08-bdea-fa3e6852352c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e3879d94-4136-4184-a63c-aea8e7d3e581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-261&quot;)</value>
      <webElementGuid>533473b5-7dde-4755-ac9f-5b41cb003963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-261']</value>
      <webElementGuid>e5ed4361-14e0-41af-a4f6-5ef28a5ad029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[4]/div/div[2]/div[5]/div/div[2]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>513542fa-868e-4ae0-b71e-fc3aeb99a8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>c462c779-e110-4288-969e-45db2f3c6829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-261' and @placeholder = 'Tuliskan Pertanyaan Disini']</value>
      <webElementGuid>78c199ed-f4c2-4089-8298-ada1df424361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
