<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__input-235</name>
   <tag></tag>
   <elementGuidId>8d6b1199-797f-48fc-a036-4dc623f6e19a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-235</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-235']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fede0c57-8b68-49c6-a771-00b4d2b07319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-235</value>
      <webElementGuid>ad224965-f87e-4d60-82d0-c047d17201e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tuliskan deskripsi singkat mengenai kursus ini</value>
      <webElementGuid>d36a45cb-9927-4abf-8d23-9d7d5b61c7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>da98fbd0-333e-4c35-b144-f95718378b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-235&quot;)</value>
      <webElementGuid>9b471dc2-de5c-46dd-890e-edee881ca4d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-235']</value>
      <webElementGuid>d2f853b6-6d0a-4bd9-99b6-c998f5421043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[3]/div/div[2]/div/div/div/textarea</value>
      <webElementGuid>047dc198-6b45-41d3-abd8-1807de95ae88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>745c61d3-8486-4d76-92fe-329b75c9bf1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-235' and @placeholder = 'Tuliskan deskripsi singkat mengenai kursus ini']</value>
      <webElementGuid>09499d2f-529f-40f7-a73b-3ee4a3bc9b29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
