<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Spesialisasi_input-253</name>
   <tag></tag>
   <elementGuidId>8e7b02bf-a602-493e-be76-7a891117d58b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-253</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-253']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3feae511-bb90-4fbc-838c-bbaaaaed60e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-253</value>
      <webElementGuid>e8cd3be3-232f-45e4-91f9-b2824f129146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f36434f-df2e-45a9-bb9c-f39d57132586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-253&quot;)</value>
      <webElementGuid>77b1305c-aeba-4063-ade0-a9f243adefc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-253']</value>
      <webElementGuid>82fc0bde-6267-4b6a-9336-1cc6d90c471f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>e043451d-c395-432a-b264-e29a584877fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7519e535-aea2-4f0d-b187-e3181d7f0532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-253' and @type = 'text']</value>
      <webElementGuid>41d78cd6-26da-4ff7-adad-b5d1802e9db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
