<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Masuk</name>
   <tag></tag>
   <elementGuidId>18fb91d5-adab-4161-b695-664dd7787a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-capitalize.v-btn.v-btn--outlined.v-btn--router.theme--light.v-size--default.primary--text > span.v-btn__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/header/div/div/div[4]/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50f49415-a2e5-4f8f-ad60-166846286f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>c2ac7577-94ab-4e55-b5a2-d0fda55e12e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Masuk </value>
      <webElementGuid>60455bf3-9b4c-47c6-a472-0604a6cf5a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[1]/div[@class=&quot;container&quot;]/header[@class=&quot;mt-0 v-sheet theme--light v-toolbar v-toolbar--flat v-app-bar v-app-bar--elevate-on-scroll v-app-bar--fixed v-app-bar--hide-shadow&quot;]/div[@class=&quot;v-toolbar__content&quot;]/div[@class=&quot;container d-flex&quot;]/div[4]/a[@class=&quot;text-capitalize v-btn v-btn--outlined v-btn--router theme--light v-size--default primary--text&quot;]/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>4d9d77ea-a994-4c70-8b05-91b0fb24bc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/header/div/div/div[4]/a[2]/span</value>
      <webElementGuid>eaa53829-2cc7-4b68-b2cc-6e2ba87dd93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::span[1]</value>
      <webElementGuid>0e879574-ed64-45ed-baba-0ecabba58451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::span[2]</value>
      <webElementGuid>e3c914ca-67ff-46a2-8926-5456434ea2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tingkatkan kemampuan para pekerjamu'])[1]/preceding::span[3]</value>
      <webElementGuid>4c12149c-5140-4fa0-85b6-1bb49c7e2fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftarkan Perusahaan'])[1]/preceding::span[3]</value>
      <webElementGuid>4be0e23a-6093-4032-b5cb-51e971e7e048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>a593e6a4-3b4d-4b1e-a10f-82537c56e4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>281b9356-beb0-4012-ba50-f1c15588606d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Masuk ' or . = ' Masuk ')]</value>
      <webElementGuid>c5feccbe-4891-4d36-ad84-4f962878cc56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
