<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Masuk_lds-ellipsis</name>
   <tag></tag>
   <elementGuidId>41dc6ae5-3637-4484-8158-a52e2540b03c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lds-ellipsis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/form/div[3]/div[2]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76b956cf-076c-4161-88cd-6098c6c18902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lds-ellipsis</value>
      <webElementGuid>ce07d446-113f-4531-8c7c-a755a3be5d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-7&quot;]/div[@class=&quot;container contain&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;v-overlay v-overlay--active theme--dark&quot;]/div[@class=&quot;v-overlay__content&quot;]/div[@class=&quot;loader&quot;]/div[@class=&quot;lds-ellipsis&quot;]</value>
      <webElementGuid>1a846a8e-71ab-4357-912b-651400adbc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60beb966-2b58-4535-9f16-7fae2e84148d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lds-ellipsis</value>
      <webElementGuid>b5d39ae6-012d-4755-bb5a-b7e1db756515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-7&quot;]/div[@class=&quot;container contain&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;v-overlay v-overlay--active theme--dark&quot;]/div[@class=&quot;v-overlay__content&quot;]/div[@class=&quot;loader&quot;]/div[@class=&quot;lds-ellipsis&quot;]</value>
      <webElementGuid>ac8b0650-486e-438e-9878-f325760bbcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ffa768a-17d9-4d2a-8e3d-e39f9baf8711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lds-ellipsis</value>
      <webElementGuid>8065d76b-a546-4027-9ff1-ac5cbf71db4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-7&quot;]/div[@class=&quot;container contain&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;v-overlay v-overlay--active theme--dark&quot;]/div[@class=&quot;v-overlay__content&quot;]/div[@class=&quot;loader&quot;]/div[@class=&quot;lds-ellipsis&quot;]</value>
      <webElementGuid>bc3b33ae-4ea0-44ab-94ef-5bb5668a35c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div[3]/div[2]/div[2]/div/div</value>
      <webElementGuid>4fe82a5c-cf38-4c9a-becc-ce9db10441ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::div[5]</value>
      <webElementGuid>386104dd-ecdc-4f79-b9f0-6f5cf857fbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingat Saya'])[1]/following::div[9]</value>
      <webElementGuid>28e572f6-1cb4-48ff-bae6-2f757361dd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>26f543eb-e6bd-42b6-b41f-db430d71e00a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
