<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Perusahaan_input-8</name>
   <tag></tag>
   <elementGuidId>b3b8904b-e173-49d6-8f9e-6030a5cafb3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a368d13a-22ad-401d-a243-b33a22c9f336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-8</value>
      <webElementGuid>627c15e8-4346-4788-b62d-cc08558ee74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bd165fe-bd57-4fba-af7d-2974f2fe3f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-8&quot;)</value>
      <webElementGuid>a23ddaa4-7202-4da7-b748-abd76cb1e35c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-8']</value>
      <webElementGuid>5fdde9e2-6227-4e93-9d2e-17a9c641206b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>90073599-09b5-4180-8520-a6c67d411ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>77cce6a0-5855-496f-aba1-04852ebb752f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-8' and @type = 'text']</value>
      <webElementGuid>d157f549-5bb6-4208-8731-7c0d0f8a8302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
