<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_input-11</name>
   <tag></tag>
   <elementGuidId>63c558b7-2a8a-462d-9b02-168d248fa8a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aec03478-c6ee-446d-9fe3-f4f9d0f50131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-11</value>
      <webElementGuid>2d1b05cb-99e8-4359-bdd5-aab765ccd3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2ff999b7-2f03-4894-8a37-b7beecc9f8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-11&quot;)</value>
      <webElementGuid>aeff2c91-3076-4acf-924c-37eb83763b62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-11']</value>
      <webElementGuid>8d59dcb1-59fe-4c46-8ee8-06eb21a863f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>85dfd23b-57cd-4647-a793-c81fa63165b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>972d140d-98d7-4aa1-8c4e-327d7134b6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-11' and @type = 'password']</value>
      <webElementGuid>9b9487c8-d946-4bd6-acc6-286193300601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
