<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_input-109</name>
   <tag></tag>
   <elementGuidId>ebd8ad5e-b60a-4358-9f08-57131ba9ae14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-109</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-109']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfc914ad-43bc-4650-b39a-0eb6babf7f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-109</value>
      <webElementGuid>3a55c55a-84b9-4fc4-829f-190d9b76c440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fe86c8ed-d7d9-477e-a586-4efa2d4e434d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-109&quot;)</value>
      <webElementGuid>ead442da-1524-4e8a-b513-67e044dd9cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55a2637f-da38-4e00-8505-9ebcbeee0494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-109</value>
      <webElementGuid>d933f1a1-28bd-44d5-a932-cc64ac7cc83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4807322a-3f56-4a16-96e5-dc9f62a08749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-109&quot;)</value>
      <webElementGuid>13a7e27e-ac27-48a6-ba17-c7f5b1e69050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-109']</value>
      <webElementGuid>f5c7600e-5348-48be-b1c9-5de902302dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>489c9239-d3fa-40b3-9ce0-10b718f65a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>95346045-0d95-4297-89f9-55c9f05a8937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-109' and @type = 'password']</value>
      <webElementGuid>c5b232d4-8d3f-41c8-8283-8ac3ffe6c25b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
